### ISSUE TITLE
Crumb trail link broken in 0.16.3

### ISSUE THREAD

**Issue by MarkANeves** [vmware-tanzu/octant#1937] opened 2021-02-02 11:10 UTC
When clicking on the second link of a crumb trial (e.g. clicking on "Pods" in the crumb trail "Workloads -> Pods -> [podname]", the link is broken and you get a "Not found" error

Here's the link address of the "Pods" link on my minikube instance when looking at a pod:
http://127.0.0.1:7777/#/overview/namespace/default/workloads/pods/hello-minikube-6ddfcc9757-sq99x/%5Coverview%5Cnamespace%5Cdefault%5Cworkloads%5Cpods

The same happens for all other categories of objects

**What did you expect to happen:**
Expected to go back to the view showing existing instances of the object type

**Environment:**
Version:  0.16.3
Git commit:  656c7404e529262861eacb13e88d33dccd6035bf
Built:  2020-12-09T23:59:19Z

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

Windows 10

**Comment by GuessWhoSamFoo** [comment] 2021-02-03 20:54
duplicate of #1901

**Closed by GuessWhoSamFoo** 2021-02-03 20:54 UTC
