### ISSUE TITLE
missing service class insides

### ISSUE THREAD

**Issue by n-able-consulting** [vmware-tanzu/octant#937] opened 2020-05-14 07:44 UTC
Before I write down 'a wish' I want to compliment and thank you all with the marvelous work that is Octant!

**Describe the problem/challenge you have**
I have bare-metal clusters, so I provide my own storage. In this case I use glusterFS. Octant offers me no way to see the Storage Class. 

**Describe the solution you'd like**
I would have expected storage classes in the cluster-overview underneath storage.

**Environment:**

- Octant version (use `octant version`): 
Version:  0.12.1
Git commit:  870ee5775b84981ecc8f01e9a90f5182972c56bf
Built:  2020-04-22T23:05:24Z

- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):
Ubuntu 20.04

**Comment by GuessWhoSamFoo** [comment] 2020-05-15 18:19
duplicate of #381

**Comment by wwitzel3** [comment] 2020-05-20 16:03
thanks @GuessWhoSamFoo closing this and moving original to sprint backlog in its place

**Closed by wwitzel3** 2020-05-20 16:03 UTC
Labels: duplicate
