### ISSUE TITLE
Logging activity in terminal when unauthorized consumes a lot of CPU.

### ISSUE THREAD

**Issue by deorbit** [vmware-tanzu/octant#424] opened 2019-11-15 00:47 UTC
`octant: stable 0.9.1`

Because of the excellence of Octant, I solved the problem I was troubleshooting with my CRDs quite quickly, but neglected to terminate Octant. I have temporary credentials with this cluster, so eventually Octant started complaining about access. The first indication of this was excessive fan noise from my laptop. A survey of processes showed multiple log entries per second in the Octant terminal tab to the effect of: `E1114 19:39:36.368682   27217 reflector.go:125] github.com/vmware-tanzu/octant/internal/objectstore/informer.go:63: Failed to list *unstructured.Unstructured: Unauthorized`

Terminating Octant terminated the fan noise.

**Comment by wwitzel3** [comment] 2019-11-24 18:14
This is a problem we need to some up the a good solution for.

@bryanl and @GuessWhoSamFoo We will probably end up having to vendor the part of the code that logs out the error. Currently we pass off control to this reflector code and if our authorization fails/goes away, we have no way of interrupting the control flow.

related #207

**Comment by wwitzel3** [comment] 2020-01-24 19:42
Closing this as a duplicate of #207 

Will use that issue to track the work around this.

**Closed by wwitzel3** 2020-01-24 19:42 UTC
Labels: api, bug, duplicate
