### ISSUE TITLE
Blank page in browser (0.8.0, Windows)

### ISSUE THREAD

**Issue by maehld** [vmware-tanzu/octant#355] opened 2019-10-18 07:16 UTC
I've downloaded Octant 0.8.0 and it does only show a blank page in all my browsers (edge dev, chrome, firefox)

From the log it seems as if the Content-Type for JavaScript-files is wrong. Here's an excerpt:

Loading module from “http://127.0.0.1:7777/main-es2015.f3cf8b8bca1b3debed1e.js” was blocked because of a disallowed MIME type (“text/plain”).

I'm using Octant on Windows 10.

**Comment by wwitzel3** [comment] 2019-10-18 15:50
I am unable to reproduce this issue on Windows 10 with Chrome, FF, or Edge. If possible, could you provide the output of the web console and the network pane for any of the mention browsers.

Also, if you re-start Octant using the `-v` switch and provide the output of the verbose logging, we might be able to see something there as well.

![image](https://user-images.githubusercontent.com/27317/67108817-4c133f00-f19d-11e9-80fd-986b15ca53e6.png)

**Comment by wwitzel3** [comment] 2019-10-18 15:51
When grabbing the Network Pane out, please use Ctrl+F5 to refresh the page (to avoid using the browser cache).

**Comment by maehld** [comment] 2019-10-21 07:21
Hi. Here is a screenshot of Edge Dev and the corresponding verbose log of octant.

![image](https://user-images.githubusercontent.com/7596/67184298-c208e780-f3e3-11e9-8f8e-87c4be7ab992.png)

[temp_octant_log.txt](https://github.com/vmware-tanzu/octant/files/3749479/temp_octant_log.txt)

**Comment by maehld** [comment] 2019-10-21 07:23
It's the same error on stable chrome. The old Edge browser (not based on Chromium) shows the page.

**Comment by maehld** [comment] 2019-10-21 07:33
I've tried to understand Go's http FileServer and it seems as if it never delivers text/javascript content types. But as you're not able to reproduce this error could that be a setting in my browsers?

**Comment by wwitzel3** [comment] 2019-10-25 19:13
@maehld did you ever get a chance to tryout the patch I suggested?

**Comment by maehld** [comment] 2019-10-28 07:35
@wwitzel3 not yet. I'll give it a go today and will let you know.

**Comment by maehld** [comment] 2019-10-29 10:15
@wwitzel3  I have trouble building octant on Windows. If I "go get" it, it is missing the presumably pregenerated frontend. Do you have a quick tip?

**Comment by wwitzel3** [comment] 2019-10-29 14:44
Ahh, yeah, so you would need to have npm and node and node installed and then you would run the following to build the front end.

```
cd web
npm run build
go generate ./web
```

So you would manually clone the repo (instead of `go get`). Run those commands to generate the UI and then go back to the root folder of the repo and run: `go run ./cmd/octant/main.go -v`

**Comment by wwitzel3** [comment] 2019-10-29 14:45
If that is too much hassle, I can build a binary for you with the fix and post a link so you can try it out (if you're comfortable with that).

**Comment by andrewsav-datacom** [comment] 2019-10-29 19:43
I'm having the same issue, so the OP is not alone

**Comment by maehld** [comment] 2019-10-29 21:19
@wwitzel3 go generate was the missing link. I've built octant with your gist and it works perfectly. Thanks.

**Comment by wwitzel3** [comment] 2019-10-29 22:30
@maehld Thank you so much for taking the time to test that! I will get a PR up shortly so this can be merged for the nightly build and the next release.

**Closed** 2019-10-29 23:51 UTC
Labels: api, bug
