### ISSUE TITLE
Octant has a delay when clicking a link

### ISSUE THREAD

**Issue by bryanl** [vmware-tanzu/octant#671] opened 2020-02-12 11:51 UTC
When clicking a link, Octant delays for ~1 second before updating the view.

goals:
* Figure out where the delay is coming from
* Remove the delay

additional notes:
* This may be related to tables re-rendering themselves after the initial load

![Screen Recording 2020-02-12 at 6 50 22 AM mov](https://user-images.githubusercontent.com/240/74332606-1c97cc00-4d64-11ea-9412-ac3f288e7348.gif)

**Comment by wwitzel3** [comment] 2020-02-12 12:29
I see this behavior on other pages as well, it seems to do with the set content path call and our streaming loop.

Areas I'd look in to when starting on this:
- ensure set content path interrupts and sends new steam content (pretty sure it does)
- look at component rendering
- only send changes to stream

**Comment by GuessWhoSamFoo** [comment] 2020-02-14 17:44
Dived into this a little bit - currently suspect the problem is occurring on the backed. Tested this by turning off change detection for multiple components and the delay after clicking a link remains.

**Comment by wwitzel3** [comment] 2020-02-14 18:11
I'm wondering if there is some hiccup between when the SetContentPath cancels the context and when the stream sends out the refreshed / new data.

**Comment by GuessWhoSamFoo** [comment] 2020-03-21 01:43
Going to close this for now. We can reopen if responsiveness starts to decrease as features are added. Ideally we'd have benchmarking for various aspects of the code base.

**Closed by GuessWhoSamFoo** 2020-03-21 01:43 UTC
Labels: bug
