### ISSUE TITLE
Resource Viewer layout continually redraws itself

### ISSUE THREAD

**Issue by jpreese** [vmware-tanzu/octant#1702] opened 2020-12-02 18:10 UTC
**What steps did you take and what happened:**
After setting my Kubernetes context and running `octant`:

- Navigated to the `Discovery and Load Balancing` section.
- Clicked on `Ingresses`
- Selected an ingress and clicked `Resource Viewer`

The Resource Viewer displays the resources, but every 2-3 seconds the layout is redrawn (without touching anything). This makes it so that its not possible to move the boxes around and take a picture of the layout. Or, at a minimum, be able to look at the diagram effectively.

**What did you expect to happen:**

The Resource Viewer to show the resources, and allow me to move the resources around in the UI.

**Environment:**

- Octant version (use `octant version`): 
```
Version:  0.16.1
Git commit:  8aebb34922f83894fb02ad393740e96ee1b3d8fe
Built:  2020-10-08T02:48:58Z
```

- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-gke.20", GitCommit:"0ac5f81eecab42bff5ef74f18b99d8896ba7b89b", GitTreeState:"clean", BuildDate:"2020-09-09T00:48:20Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}
```

- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): `macOS 10.15.6`

**Comment by wwitzel3** [comment] 2020-12-09 20:39
Hi @jpreese thank you for reporting this, I'm going to close this as a duplicate of #236

**Closed by wwitzel3** 2020-12-09 20:39 UTC
Labels: bug, duplicate, resourceviewer
