### ISSUE TITLE
Handle Octant indefinitely spamming cluster api on bad request

### ISSUE THREAD

**Issue by connor0209** [vmware-tanzu/octant#556] opened 2020-01-22 14:15 UTC
When a user's token to authenticate themselves against the cluster times out, a bad request response error is returned. Octant then goes on to spam the cluster with thousands of requests indefinitely, until closed. Implementing an exponential backoff would help to prevent cases like this to avoid DOS attacks.

**Comment by moderation** [comment] 2020-01-24 19:16
+1 I was just about to create this exact issue but the handy Github feature showed me this existing issue.

We have a locked down cluster that has an additional layer of authentication that developers need to go through. The login to the cluster is time limited to a couple of hours and then logs out. When the logout occurs and Octant is running it DOS's the API server and returns the following errors:
```
Response: {"error":"invalid_grant","error_description":"MSIS9615: The refresh token received in \u0027refresh_token\u0027 parameter has expired."}
E0117 17:58:05.318424   12794 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *unstructured.Unstructured: Get https://<APIFQDN>:<APIPORT>/apis/apps/v1/namespaces/<NAMESPACE>/deployments?
limit=500&resourceVersion=0: failed to refresh token: oauth2: cannot fetch token: 400 Bad Request
```
To give you a sense of how bad this is our internal tools captured Octant issuing between 350K and 750K requests per hour for multiple hours.

Feature request: terminate on timeout login details and / or 400 requests.

**Comment by wwitzel3** [comment] 2020-01-24 19:40
This is a duplicate of #207 closing this and will track the work on this issue there.

**Closed by wwitzel3** 2020-01-24 19:40 UTC
Labels: api, bug, duplicate
