### ISSUE TITLE
Octant crashes when trying to explore a PV

### ISSUE THREAD

**Issue by gregnsk** [vmware-tanzu/octant#819] opened 2020-04-06 15:47 UTC
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
Installed Octant on MacOS 
Connected to a K8s cluster (1.18)
Browsed to a PVC, and tried to click on the PV

![image](https://user-images.githubusercontent.com/13031997/78577344-c898e900-77e2-11ea-94cb-d3c3e05e9918.png)

The browser reports: "Lost connection to Octant service, Retrying"

In the shell window:
2020-04-06T08:38:16.976-0700	INFO	objectstore/dynamic_cache.go:205	backing off for storage.k8s.io/v1beta1, Kind=CSINodeInfo (1.088724157s)	{"component": "websocket-client", "client-id": "a112aef4-781c-11ea-8a5d-823726822c01", "poller-name": "navigation", "poller-instance": "bea0a499-45e9-467c-b46c-a1dcadaf8591"}
2020-04-06T08:38:16.976-0700	ERROR	api/navigation_manager.go:97	load namespaces	{"component": "websocket-client", "client-id": "a112aef4-781c-11ea-8a5d-823726822c01", "poller-name": "navigation", "poller-instance": "bea0a499-45e9-467c-b46c-a1dcadaf8591", "err": "unable to generate navigation for module cluster-overview: generate entries for Custom Resources: listing custom resources for \"csinodeinfos.storage.k8s.io\": check access to list CacheKey[APIVersion='storage.k8s.io/v1beta1', Kind='CSINodeInfo']: unable to get resource for group kind CSINodeInfo.storage.k8s.io: no matches for kind \"CSINodeInfo\" in group \"storage.k8s.io\""}
github.com/vmware-tanzu/octant/internal/api.(*NavigationManager).runUpdate.func1
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/api/navigation_manager.go:97
github.com/vmware-tanzu/octant/internal/api.(*InterruptiblePoller).Run.func1
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/api/poller.go:86
github.com/vmware-tanzu/octant/internal/api.(*InterruptiblePoller).Run
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/api/poller.go:95
github.com/vmware-tanzu/octant/internal/api.(*NavigationManager).Start
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/api/navigation_manager.go:86
2020-04-06T08:38:17.205-0700	ERROR	api/navigation_manager.go:97	load namespaces	{"component": "websocket-client", "client-id": "a1aff902-781c-11ea-8a5d-823726822c01", "poller-name": "navigation", "poller-instance": "aac95e13-35e1-464e-947f-a037072b3bab", "err": "unable to generate navigation for module cluster-overview: generate entries for Custom Resources: listing custom resources for \"csinodeinfos.storage.k8s.io\": check access to list CacheKey[APIVersion='storage.k8s.io/v1beta1', Kind='CSINodeInfo']: unable to get resource for group kind CSINodeInfo.storage.k8s.io: no matches for kind \"CSINodeInfo\" in group \"storage.k8s.io\""}
github.com/vmware-tanzu/octant/internal/api.(*NavigationManager).runUpdate.func1
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/api/navigation_manager.go:97
github.com/vmware-tanzu/octant/internal/api.(*InterruptiblePoller).Run.func1
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/api/poller.go:86
github.com/vmware-tanzu/octant/internal/api.(*InterruptiblePoller).Run
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/api/poller.go:95
github.com/vmware-tanzu/octant/internal/api.(*NavigationManager).Start
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/api/navigation_manager.go:86
2020-04-06T08:38:18.571-0700	INFO	objectstore/dynamic_cache.go:205	backing off for storage.k8s.io/v1beta1, Kind=CSINodeInfo (2.153530841s)	{"component": "websocket-client", "client-id": "a1aff902-781c-11ea-8a5d-823726822c01", "poller-name": "navigation", "poller-instance": "aac95e13-35e1-464e-947f-a037072b3bab"}
2020-04-06T08:38:18.571-0700	ERROR	api/navigation_manager.go:97	load namespaces	{"component": "websocket-client", "client-id": "a1aff902-781c-11ea-8a5d-823726822c01", "poller-name": "navigation", "poller-instance": "aac95e13-35e1-464e-947f-a037072b3bab", "err": "unable to generate navigation for module cluster-overview: generate entries for Custom Resources: listing custom resources for \"csinodeinfos.storage.k8s.io\": check access to list CacheKey[APIVersion='storage.k8s.io/v1beta1', Kind='CSINodeInfo']: unable to get resource for group kind CSINodeInfo.storage.k8s.io: no matches for kind \"CSINodeInfo\" in group \"storage.k8s.io\""}
github.com/vmware-tanzu/octant/internal/api.(*NavigationManager).runUpdate.func1
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/api/navigation_manager.go:97
github.com/vmware-tanzu/octant/internal/api.(*InterruptiblePoller).Run.func1
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/api/poller.go:86
github.com/vmware-tanzu/octant/internal/api.(*InterruptiblePoller).Run
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/api/poller.go:95
github.com/vmware-tanzu/octant/internal/api.(*NavigationManager).Start
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/api/navigation_manager.go:86
2020-04-06T08:38:22.443-0700	ERROR	api/navigation_manager.go:97	load namespaces	{"component": "websocket-client", "client-id": "a1aff902-781c-11ea-8a5d-823726822c01", "poller-name": "navigation", "poller-instance": "aac95e13-35e1-464e-947f-a037072b3bab", "err": "unable to generate navigation for module cluster-overview: generate entries for Custom Resources: listing custom resources for \"csinodeinfos.storage.k8s.io\": check access to list CacheKey[APIVersion='storage.k8s.io/v1beta1', Kind='CSINodeInfo']: unable to get resource for group kind CSINodeInfo.storage.k8s.io: no matches for kind \"CSINodeInfo\" in group \"storage.k8s.io\""}
github.com/vmware-tanzu/octant/internal/api.(*NavigationManager).runUpdate.func1
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/api/navigation_manager.go:97
github.com/vmware-tanzu/octant/internal/api.(*InterruptiblePoller).Run.func1
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/api/poller.go:86
github.com/vmware-tanzu/octant/internal/api.(*InterruptiblePoller).Run
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/api/poller.go:95
github.com/vmware-tanzu/octant/internal/api.(*NavigationManager).Start
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/api/navigation_manager.go:86
2020-04-06T08:38:22.443-0700	INFO	objectstore/dynamic_cache.go:205	backing off for storage.k8s.io/v1beta1, Kind=CSINodeInfo (4.115710485s)	{"component": "websocket-client", "client-id": "a1aff902-781c-11ea-8a5d-823726822c01", "poller-name": "navigation", "poller-instance": "aac95e13-35e1-464e-947f-a037072b3bab"}
2020-04-06T08:38:27.105-0700	ERROR	api/navigation_manager.go:97	load namespaces	{"component": "websocket-client", "client-id": "a1aff902-781c-11ea-8a5d-823726822c01", "poller-name": "navigation", "poller-instance": "aac95e13-35e1-464e-947f-a037072b3bab", "err": "unable to generate navigation for module cluster-overview: generate entries for Custom Resources: listing custom resources for \"csinodeinfos.storage.k8s.io\": check access to list CacheKey[APIVersion='storage.k8s.io/v1beta1', Kind='CSINodeInfo']: unable to get resource for group kind CSINodeInfo.storage.k8s.io: no matches for kind \"CSINodeInfo\" in group \"storage.k8s.io\""}
github.com/vmware-tanzu/octant/internal/api.(*NavigationManager).runUpdate.func1
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/api/navigation_manager.go:97
github.com/vmware-tanzu/octant/internal/api.(*InterruptiblePoller).Run.func1
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/api/poller.go:86
github.com/vmware-tanzu/octant/internal/api.(*InterruptiblePoller).Run
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/api/poller.go:95
github.com/vmware-tanzu/octant/internal/api.(*NavigationManager).Start
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/api/navigation_manager.go:86
2020-04-06T08:38:27.105-0700	INFO	objectstore/dynamic_cache.go:205	backing off for storage.k8s.io/v1beta1, Kind=CSINodeInfo (8.526222851s)	{"component": "websocket-client", "client-id": "a1aff902-781c-11ea-8a5d-823726822c01", "poller-name": "navigation", "poller-instance": "aac95e13-35e1-464e-947f-a037072b3bab"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x2129a21]

goroutine 255 [running]:
github.com/vmware-tanzu/octant/internal/printer.(*PersistentVolumeConfiguration).Create(0xc0006a6550, 0x0, 0x3bca540, 0xc000f4b040, 0x3baa9c0, 0xc0004cf1a8, 0x2125804, 0x2516700, 0xc0008c2800)
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/printer/persistentvolume.go:163 +0x6e1
github.com/vmware-tanzu/octant/internal/printer.defaultPersistentVolumeConfig(0xc0008bea00, 0x0, 0x3bca540, 0xc000f4b040, 0x3baa9c0, 0xc0004cf1a8, 0x245eea0, 0xc000772660, 0x0)
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/printer/persistentvolume.go:127 +0x63
github.com/vmware-tanzu/octant/internal/printer.(*persistentVolumeHandler).Config(0xc000772660, 0x0, 0x3bca540, 0xc000f4b040, 0x3baa9c0, 0xc0004cf1a8, 0x2415800, 0xc001168c80)
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/printer/persistentvolume.go:109 +0x54
github.com/vmware-tanzu/octant/internal/printer.PersistentVolumeHandler(0x3baa600, 0xc001168c80, 0xc0008bea00, 0x0, 0x3bca540, 0xc000f4b040, 0x3baa9c0, 0xc0004cf1a8, 0x0, 0x0, ...)
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/printer/persistentvolume.go:72 +0xc1
reflect.Value.call(0x236b920, 0x39a0168, 0x13, 0x258603e, 0x4, 0xc0006a6ab8, 0x3, 0x3, 0x100bebf, 0x2421140, ...)
	/usr/local/Cellar/go/1.14.1/libexec/src/reflect/value.go:460 +0x8ab
reflect.Value.Call(0x236b920, 0x39a0168, 0x13, 0xc0006a6ab8, 0x3, 0x3, 0xc0006a8770, 0xe, 0x73)
	/usr/local/Cellar/go/1.14.1/libexec/src/reflect/value.go:321 +0xb4
github.com/vmware-tanzu/octant/internal/printer.(*Resource).Print(0xc000752660, 0x3baa600, 0xc001168c80, 0x3b7b300, 0xc0008bea00, 0x3baaa00, 0xc0001bcbd0, 0x23ea3c0, 0xc0006a6bc8, 0xc0006a6bf8, ...)
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/printer/printer.go:77 +0x472
github.com/vmware-tanzu/octant/internal/describer.(*Object).addSummaryTab(0xc000f81c80, 0x3baa600, 0xc001168c80, 0x3b7b300, 0xc0008bea00, 0xc000239260, 0x3bca540, 0xc000f4b040, 0x3bc55a0, 0xc000710440, ...)
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/describer/object.go:214 +0xab
github.com/vmware-tanzu/octant/internal/describer.(*Object).Describe(0xc000f81c80, 0x3baa600, 0xc001168c80, 0x0, 0x0, 0x3bca540, 0xc000f4b040, 0x3bc55a0, 0xc000710440, 0xc000791b00, ...)
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/describer/object.go:154 +0xf52
github.com/vmware-tanzu/octant/internal/modules/clusteroverview.(*ClusterOverview).Content(0xc001081840, 0x3baa600, 0xc001168c80, 0xc000fce590, 0x22, 0xc0004cf178, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/modules/clusteroverview/clusteroverview.go:167 +0x750
github.com/vmware-tanzu/octant/internal/api.(*ContentManager).generateContent(0xc000b94f40, 0x3baa600, 0xc001168c80, 0x3bc91e0, 0xc00016c000, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/api/content_manager.go:161 +0x320
github.com/vmware-tanzu/octant/internal/api.(*ContentManager).runUpdate.func1(0x3baa600, 0xc001168c80, 0x485b560)
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/api/content_manager.go:115 +0xe0
github.com/vmware-tanzu/octant/internal/api.(*InterruptiblePoller).Run.func1(0x3baa600, 0xc000b94f00, 0x3bbae80, 0xc0004cebf0, 0xc0006a7e77, 0xc00119cd80, 0xc0004f7590, 0xc000c314a0, 0x3b9aca00)
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/api/poller.go:86 +0x271
github.com/vmware-tanzu/octant/internal/api.(*InterruptiblePoller).Run(0xc000c37060, 0x3baa600, 0xc000b94f00, 0xc00119cd80, 0xc000c314a0, 0x3b9aca00)
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/api/poller.go:95 +0x2ff
github.com/vmware-tanzu/octant/internal/api.(*ContentManager).Start(0xc000b94f40, 0x3baa600, 0xc000b94f00, 0x3bc91e0, 0xc00016c000, 0x3b78cc0, 0xc0011e2300)
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/api/content_manager.go:105 +0x1c7
created by github.com/vmware-tanzu/octant/internal/api.(*WebsocketState).Start
	/private/tmp/octant-20200330-46047-1cpjkwt/src/github.com/vmware-tanzu/octant/internal/api/websocket_state.go:142 +0x9b

**What did you expect to happen:**
PV details

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Octant version (use `octant version`): 
Version:  0.11.1
Git commit:  a5f7847a7e21d781fdb7edd5389b04edc2ca6b87
Built:  2020-03-30T19:51:23Z
- Kubernetes version (use `kubectl version`):
gregorytouretsky@Gregorys-MacBook-Pro ~ % kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):
macOS 10.15.4

**Comment by GuessWhoSamFoo** [comment] 2020-04-06 17:08
I think this is a duplicate of #814 and fix in #817

**Comment by wwitzel3** [comment] 2020-04-06 17:16
Thanks @GuessWhoSamFoo.

**Closed** 2020-04-06 21:50 UTC
Labels: api, bug
