### ISSUE TITLE
Links to CRD types stop working

### ISSUE THREAD

**Issue by ssdowdavalon** [vmware-tanzu/octant#753] opened 2020-03-05 22:06 UTC
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
After working for a while, links to custom resources (certificates, certificaterequests, orders - all cert-manager.io) stop working and direct to top-level namespace page.

**What did you expect to happen:**
I expected to see the customs types that were there before.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Octant version (use `octant version`): 0.10.2
- Kubernetes version (use `kubectl version`): 1.14 (eks)
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): macOS 10.15.13/Chrome

**Comment by GuessWhoSamFoo** [comment] 2020-03-05 22:17
Possible duplicate of #672 and just pushed #751 as the fix unless there is something else that breaks CRD links

**Comment by GuessWhoSamFoo** [comment] 2020-03-10 19:16
going to close this. If this issue still exists in the next release, feel free to ping to reopen.

**Closed by GuessWhoSamFoo** 2020-03-10 19:16 UTC
Labels: bug, duplicate
