### ISSUE TITLE
Ingressd

### ISSUE THREAD

**Issue by wpfeiffe-arbfile** [vmware-tanzu/octant#2443] opened 2021-05-11 23:04 UTC
**What steps did you take and what happened:**
Run octant.exe in windows (octant_0.19.0_Windows-64bit).  It pops up chrome running octant page.  Connects to my cluster just fine.  When I go to look at Ingresses, octant produces errors in log and never shows ingress object:

From the log:

2021-05-11T19:01:53.760-0400    ERROR   api/content_manager.go:158      generate content        {"client-id": "81cc0a9a-b2aa-11eb-bf16-54c3aad0520e", "err": "generate content: scheme convert: converting (v1beta1.Ingress) to (v1.Ingress): unknown conversion", "content-path": "overview/namespace/elastic-trs/discovery-and-load-balancing/ingresses"}
github.com/vmware-tanzu/octant/internal/api.(*ContentManager).runUpdate.func1
        /__w/octant/octant/internal/api/content_manager.go:158
github.com/vmware-tanzu/octant/internal/api.(*InterruptiblePoller).Run.func1
        /__w/octant/octant/internal/api/poller.go:86
github.com/vmware-tanzu/octant/internal/api.(*InterruptiblePoller).Run
        /__w/octant/octant/internal/api/poller.go:95
github.com/vmware-tanzu/octant/internal/api.(*ContentManager).Start
        /__w/octant/octant/internal/api/content_manager.go:132

**What did you expect to happen:**
Show ingress object

**Anything else you would like to add:**
Note the api for the ingress is v1beta1.  

**Environment:**

- Octant version (use `octant version`):  (octant_0.19.0_Windows-64bit)
- Kubernetes version (use `kubectl version`): 1.19.7
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Windows 10 20H2

**Comment by wwitzel3** [comment] 2021-06-23 17:39
Thank you for reporting this, we are fixing this issue now. Duplicate of #2063

**Closed by wwitzel3** 2021-06-23 17:39 UTC
