### ISSUE TITLE
support opening a Pod terminal for another container than the first

### ISSUE THREAD

**Issue by jstrachan** [vmware-tanzu/octant#914] opened 2020-05-06 15:47 UTC
**Describe the problem/challenge you have**
The terminal view in octant is awesome. However it is currently hard coded to only support the first container:
https://github.com/vmware-tanzu/octant/blob/master/internal/modules/overview/terminalviewer/terminalviewer.go#L56-L59

It would be nice to be able to open a terminal in any container. Sometimes the first container doesn't have a shell binary like sh/bash (e.g. tekton pipelines)

**Describe the solution you'd like**
it would be awesome if there was a way to pass in the container name to open a terminal via a URL path or something; so that either octant itself or a plugin could link to a pods terminal page for a named container. If no name is specified defaulting to the first container sounds a reasonable thing to do.

e.g. on the main Pods page there could be a terminal link on each Container so that folks can decide which container they want to use to open the terminal for a Pod

BTW I tried opening terminals in a plugin and nothing seemed to work; I've a feeling terminals only work inside octant itself? I see this if I try:

```
api/content_manager.go:130  generate content  {"client-id": "63f1e32c-8fb0-11ea-934d-acde48001122", "err": "generate content: unmarshal content response: unknown view component \"terminal\"",
```

A use case for this is when using Tekton; you often want to open a terminal in the last container (as earlier containers may have terminated).

**Comment by wwitzel3** [comment] 2020-05-06 16:01
Closing this as a duplicate of #901 

cc: @GuessWhoSamFoo

**Closed by wwitzel3** 2020-05-06 16:01 UTC
Labels: duplicate

**Comment by GuessWhoSamFoo** [comment] 2020-05-07 00:17
Linking to a terminal is something discussed in the past. The way angular handles routing currently makes this difficult. We can revisit this as this is a reasonable feature to support.
